import React, { useState, useEffect } from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import {
  useGetAllStudents,
  useGetAllInstructors,
  useGetAllAircraft,
  useGetAllExercises,
  useCreateFlightLog,
} from "../hooks/useQueries";
import { calculateDuration, getCurrentDate, isValidTime, formatDuration } from "../utils/timeUtils";
import { toast } from "sonner";
import { Loader2, CheckCircle2 } from "lucide-react";
import type { FlightLog } from "../backend";

export default function LogFlightPage() {
  const [date, setDate] = useState(getCurrentDate());
  const [student, setStudent] = useState("");
  const [instructor, setInstructor] = useState("");
  const [aircraft, setAircraft] = useState("");
  const [exercise, setExercise] = useState("");
  const [flightType, setFlightType] = useState("Dual");
  const [takeoffTime, setTakeoffTime] = useState("");
  const [landingTime, setLandingTime] = useState("");
  const [landingType, setLandingType] = useState("Day");
  const [landingCount, setLandingCount] = useState("");
  const [calculatedDuration, setCalculatedDuration] = useState<number | null>(null);

  const { data: students, isLoading: studentsLoading } = useGetAllStudents();
  const { data: instructors, isLoading: instructorsLoading } = useGetAllInstructors();
  const { data: aircraftList, isLoading: aircraftLoading } = useGetAllAircraft();
  const { data: exercises, isLoading: exercisesLoading } = useGetAllExercises();
  const createFlightLog = useCreateFlightLog();

  useEffect(() => {
    if (takeoffTime && landingTime && isValidTime(takeoffTime) && isValidTime(landingTime)) {
      const duration = calculateDuration(takeoffTime, landingTime);
      if (duration > 0) {
        setCalculatedDuration(duration);
      } else {
        setCalculatedDuration(null);
      }
    } else {
      setCalculatedDuration(null);
    }
  }, [takeoffTime, landingTime]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!student || !instructor || !aircraft || !exercise) {
      toast.error("Please fill in all required fields");
      return;
    }

    if (!isValidTime(takeoffTime) || !isValidTime(landingTime)) {
      toast.error("Please enter valid times in HH:MM format");
      return;
    }

    if (calculatedDuration === null || calculatedDuration <= 0) {
      toast.error("Landing time must be after takeoff time");
      return;
    }

    const log: FlightLog = {
      id: 0n, // Placeholder - will be auto-generated by backend
      date,
      studentName: student,
      instructorName: instructor,
      aircraftRegistration: aircraft,
      exerciseName: exercise,
      flightType,
      takeoffTime,
      landingTime,
      durationMinutes: BigInt(calculatedDuration),
      landingType,
      landingCount: BigInt(landingCount || 0),
    };

    try {
      await createFlightLog.mutateAsync(log);
      toast.success("Flight log created successfully");
      
      setDate(getCurrentDate());
      setStudent("");
      setInstructor("");
      setAircraft("");
      setExercise("");
      setFlightType("Dual");
      setTakeoffTime("");
      setLandingTime("");
      setLandingType("Day");
      setLandingCount("");
      setCalculatedDuration(null);
    } catch (error) {
      console.error("Failed to create flight log:", error);
      toast.error("Failed to create flight log");
    }
  };

  const isLoading = studentsLoading || instructorsLoading || aircraftLoading || exercisesLoading;

  return (
    <div className="max-w-3xl mx-auto animate-fade-in">
      <Card>
        <CardHeader>
          <CardTitle className="font-display text-2xl">Log New Flight</CardTitle>
          <CardDescription>
            Record flight training session details
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="flex items-center justify-center py-12">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
            </div>
          ) : (
            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="space-y-2">
                <Label htmlFor="date">Date</Label>
                <Input
                  id="date"
                  type="date"
                  value={date}
                  onChange={(e) => setDate(e.target.value)}
                  required
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Student</Label>
                  <Select value={student} onValueChange={setStudent} required>
                    <SelectTrigger>
                      <SelectValue placeholder="Select student" />
                    </SelectTrigger>
                    <SelectContent>
                      {students && students.length > 0 ? (
                        students.map((s) => (
                          <SelectItem key={s.name} value={s.name}>
                            {s.name}
                          </SelectItem>
                        ))
                      ) : (
                        <div className="px-2 py-1.5 text-sm text-muted-foreground">
                          No students available
                        </div>
                      )}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label>Instructor</Label>
                  <Select value={instructor} onValueChange={setInstructor} required>
                    <SelectTrigger>
                      <SelectValue placeholder="Select instructor" />
                    </SelectTrigger>
                    <SelectContent>
                      {instructors && instructors.length > 0 ? (
                        instructors.map((i) => (
                          <SelectItem key={i.name} value={i.name}>
                            {i.name}
                          </SelectItem>
                        ))
                      ) : (
                        <div className="px-2 py-1.5 text-sm text-muted-foreground">
                          No instructors available
                        </div>
                      )}
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Aircraft</Label>
                  <Select value={aircraft} onValueChange={setAircraft} required>
                    <SelectTrigger>
                      <SelectValue placeholder="Select aircraft" />
                    </SelectTrigger>
                    <SelectContent>
                      {aircraftList && aircraftList.length > 0 ? (
                        aircraftList.map((a) => (
                          <SelectItem key={a.registration} value={a.registration}>
                            {a.registration}
                          </SelectItem>
                        ))
                      ) : (
                        <div className="px-2 py-1.5 text-sm text-muted-foreground">
                          No aircraft available
                        </div>
                      )}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label>Exercise</Label>
                  <Select value={exercise} onValueChange={setExercise} required>
                    <SelectTrigger>
                      <SelectValue placeholder="Select exercise" />
                    </SelectTrigger>
                    <SelectContent>
                      {exercises && exercises.length > 0 ? (
                        exercises.map((e) => (
                          <SelectItem key={e.name} value={e.name}>
                            {e.name}
                          </SelectItem>
                        ))
                      ) : (
                        <div className="px-2 py-1.5 text-sm text-muted-foreground">
                          No exercises available
                        </div>
                      )}
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="space-y-2">
                <Label>Flight Type</Label>
                <RadioGroup value={flightType} onValueChange={setFlightType}>
                  <div className="flex gap-4">
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="Solo" id="solo" />
                      <Label htmlFor="solo" className="font-normal cursor-pointer">Solo</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="Dual" id="dual" />
                      <Label htmlFor="dual" className="font-normal cursor-pointer">Dual</Label>
                    </div>
                  </div>
                </RadioGroup>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="takeoffTime">Takeoff Time (HH:MM)</Label>
                  <Input
                    id="takeoffTime"
                    type="text"
                    placeholder="14:30"
                    value={takeoffTime}
                    onChange={(e) => setTakeoffTime(e.target.value)}
                    required
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="landingTime">Landing Time (HH:MM)</Label>
                  <Input
                    id="landingTime"
                    type="text"
                    placeholder="16:45"
                    value={landingTime}
                    onChange={(e) => setLandingTime(e.target.value)}
                    required
                  />
                </div>
              </div>

              {calculatedDuration !== null && (
                <div className="p-4 bg-success/10 border border-success/20 rounded-md flex items-center gap-2">
                  <CheckCircle2 className="h-5 w-5 text-success" />
                  <span className="text-sm font-medium">
                    Calculated Duration: {formatDuration(calculatedDuration)}
                  </span>
                </div>
              )}

              <div className="space-y-2">
                <Label>Landing Type</Label>
                <RadioGroup value={landingType} onValueChange={setLandingType}>
                  <div className="flex gap-4">
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="Day" id="day" />
                      <Label htmlFor="day" className="font-normal cursor-pointer">Day</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="Night" id="night" />
                      <Label htmlFor="night" className="font-normal cursor-pointer">Night</Label>
                    </div>
                  </div>
                </RadioGroup>
              </div>

              <div className="space-y-2">
                <Label htmlFor="landingCount">Landing Count</Label>
                <Input
                  id="landingCount"
                  type="number"
                  min="0"
                  value={landingCount}
                  onChange={(e) => setLandingCount(e.target.value)}
                  required
                />
              </div>

              <Button
                type="submit"
                className="w-full"
                size="lg"
                disabled={createFlightLog.isPending || calculatedDuration === null}
              >
                {createFlightLog.isPending ? (
                  <>
                    <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                    Creating Flight Log...
                  </>
                ) : (
                  "Create Flight Log"
                )}
              </Button>
            </form>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
