/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Aircraft = IDL.Record({
  'totalAirframeHours' : IDL.Nat,
  'registration' : IDL.Text,
  'hourlyRate' : IDL.Nat,
  'makeModel' : IDL.Text,
  'lastMaintenanceDate' : IDL.Text,
});
export const Exercise = IDL.Record({
  'difficultyLevel' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'durationMinutes' : IDL.Nat,
});
export const Instructor = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'rating' : IDL.Text,
  'phone' : IDL.Text,
  'certificateNumber' : IDL.Text,
});
export const Student = IDL.Record({
  'totalFlightHours' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'medicalExpiry' : IDL.Text,
  'licenseNumber' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FlightLog = IDL.Record({
  'id' : IDL.Nat,
  'aircraftRegistration' : IDL.Text,
  'studentName' : IDL.Text,
  'date' : IDL.Text,
  'flightType' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'exerciseName' : IDL.Text,
  'takeoffTime' : IDL.Text,
  'landingTime' : IDL.Text,
  'landingType' : IDL.Text,
  'landingCount' : IDL.Nat,
  'instructorName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const AdminUserInfo = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
  'profile' : UserProfile,
});
export const DailySummary = IDL.Record({
  'totalFlights' : IDL.Nat,
  'totalHours' : IDL.Float64,
  'date' : IDL.Text,
});
export const MonthlySummary = IDL.Record({
  'month' : IDL.Text,
  'totalFlights' : IDL.Nat,
  'totalHours' : IDL.Float64,
});
export const AircraftHours = IDL.Record({
  'totalHours' : IDL.Float64,
  'registration' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAircraft' : IDL.Func([Aircraft], [IDL.Text], []),
  'addExercise' : IDL.Func([Exercise], [IDL.Text], []),
  'addInstructor' : IDL.Func([Instructor], [IDL.Text], []),
  'addStudent' : IDL.Func([Student], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFlightLog' : IDL.Func([FlightLog], [IDL.Nat], []),
  'createOrGetProfile' : IDL.Func([UserProfile], [UserProfile], []),
  'deleteAircraft' : IDL.Func([IDL.Text], [], []),
  'deleteExercise' : IDL.Func([IDL.Text], [], []),
  'deleteFlightLog' : IDL.Func([IDL.Nat], [], []),
  'deleteInstructor' : IDL.Func([IDL.Text], [], []),
  'deleteStudent' : IDL.Func([IDL.Text], [], []),
  'getAllAircrafts' : IDL.Func([], [IDL.Vec(Aircraft)], ['query']),
  'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getAllFlightLogs' : IDL.Func([], [IDL.Vec(FlightLog)], ['query']),
  'getAllInstructors' : IDL.Func([], [IDL.Vec(Instructor)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllUsersWithProfiles' : IDL.Func([], [IDL.Vec(AdminUserInfo)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailySummary' : IDL.Func([IDL.Text], [DailySummary], ['query']),
  'getFlightLogById' : IDL.Func([IDL.Nat], [IDL.Opt(FlightLog)], ['query']),
  'getFlightLogsByAircraft' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FlightLog)],
      ['query'],
    ),
  'getFlightLogsByDateRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(FlightLog)],
      ['query'],
    ),
  'getFlightLogsByInstructor' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FlightLog)],
      ['query'],
    ),
  'getFlightLogsByMonth' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FlightLog)],
      ['query'],
    ),
  'getFlightLogsByStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FlightLog)],
      ['query'],
    ),
  'getMonthlySummary' : IDL.Func([IDL.Text], [MonthlySummary], ['query']),
  'getTotalHoursPerAircraft' : IDL.Func(
      [],
      [IDL.Vec(AircraftHours)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAircraft' : IDL.Func([IDL.Text, Aircraft], [], []),
  'updateExercise' : IDL.Func([IDL.Text, Exercise], [], []),
  'updateFlightLog' : IDL.Func([FlightLog], [], []),
  'updateInstructor' : IDL.Func([IDL.Text, Instructor], [], []),
  'updateStudent' : IDL.Func([IDL.Text, Student], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Aircraft = IDL.Record({
    'totalAirframeHours' : IDL.Nat,
    'registration' : IDL.Text,
    'hourlyRate' : IDL.Nat,
    'makeModel' : IDL.Text,
    'lastMaintenanceDate' : IDL.Text,
  });
  const Exercise = IDL.Record({
    'difficultyLevel' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'durationMinutes' : IDL.Nat,
  });
  const Instructor = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'rating' : IDL.Text,
    'phone' : IDL.Text,
    'certificateNumber' : IDL.Text,
  });
  const Student = IDL.Record({
    'totalFlightHours' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'medicalExpiry' : IDL.Text,
    'licenseNumber' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FlightLog = IDL.Record({
    'id' : IDL.Nat,
    'aircraftRegistration' : IDL.Text,
    'studentName' : IDL.Text,
    'date' : IDL.Text,
    'flightType' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'exerciseName' : IDL.Text,
    'takeoffTime' : IDL.Text,
    'landingTime' : IDL.Text,
    'landingType' : IDL.Text,
    'landingCount' : IDL.Nat,
    'instructorName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const AdminUserInfo = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
    'profile' : UserProfile,
  });
  const DailySummary = IDL.Record({
    'totalFlights' : IDL.Nat,
    'totalHours' : IDL.Float64,
    'date' : IDL.Text,
  });
  const MonthlySummary = IDL.Record({
    'month' : IDL.Text,
    'totalFlights' : IDL.Nat,
    'totalHours' : IDL.Float64,
  });
  const AircraftHours = IDL.Record({
    'totalHours' : IDL.Float64,
    'registration' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAircraft' : IDL.Func([Aircraft], [IDL.Text], []),
    'addExercise' : IDL.Func([Exercise], [IDL.Text], []),
    'addInstructor' : IDL.Func([Instructor], [IDL.Text], []),
    'addStudent' : IDL.Func([Student], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFlightLog' : IDL.Func([FlightLog], [IDL.Nat], []),
    'createOrGetProfile' : IDL.Func([UserProfile], [UserProfile], []),
    'deleteAircraft' : IDL.Func([IDL.Text], [], []),
    'deleteExercise' : IDL.Func([IDL.Text], [], []),
    'deleteFlightLog' : IDL.Func([IDL.Nat], [], []),
    'deleteInstructor' : IDL.Func([IDL.Text], [], []),
    'deleteStudent' : IDL.Func([IDL.Text], [], []),
    'getAllAircrafts' : IDL.Func([], [IDL.Vec(Aircraft)], ['query']),
    'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getAllFlightLogs' : IDL.Func([], [IDL.Vec(FlightLog)], ['query']),
    'getAllInstructors' : IDL.Func([], [IDL.Vec(Instructor)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllUsersWithProfiles' : IDL.Func(
        [],
        [IDL.Vec(AdminUserInfo)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailySummary' : IDL.Func([IDL.Text], [DailySummary], ['query']),
    'getFlightLogById' : IDL.Func([IDL.Nat], [IDL.Opt(FlightLog)], ['query']),
    'getFlightLogsByAircraft' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FlightLog)],
        ['query'],
      ),
    'getFlightLogsByDateRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(FlightLog)],
        ['query'],
      ),
    'getFlightLogsByInstructor' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FlightLog)],
        ['query'],
      ),
    'getFlightLogsByMonth' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FlightLog)],
        ['query'],
      ),
    'getFlightLogsByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FlightLog)],
        ['query'],
      ),
    'getMonthlySummary' : IDL.Func([IDL.Text], [MonthlySummary], ['query']),
    'getTotalHoursPerAircraft' : IDL.Func(
        [],
        [IDL.Vec(AircraftHours)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAircraft' : IDL.Func([IDL.Text, Aircraft], [], []),
    'updateExercise' : IDL.Func([IDL.Text, Exercise], [], []),
    'updateFlightLog' : IDL.Func([FlightLog], [], []),
    'updateInstructor' : IDL.Func([IDL.Text, Instructor], [], []),
    'updateStudent' : IDL.Func([IDL.Text, Student], [], []),
  });
};

export const init = ({ IDL }) => { return []; };