/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminUserInfo {
  'principal' : Principal,
  'role' : UserRole,
  'profile' : UserProfile,
}
export interface Aircraft {
  'totalAirframeHours' : bigint,
  'registration' : string,
  'hourlyRate' : bigint,
  'makeModel' : string,
  'lastMaintenanceDate' : string,
}
export interface AircraftHours {
  'totalHours' : number,
  'registration' : string,
}
export interface DailySummary {
  'totalFlights' : bigint,
  'totalHours' : number,
  'date' : string,
}
export interface Exercise {
  'difficultyLevel' : string,
  'name' : string,
  'description' : string,
  'durationMinutes' : bigint,
}
export interface FlightLog {
  'id' : bigint,
  'aircraftRegistration' : string,
  'studentName' : string,
  'date' : string,
  'flightType' : string,
  'durationMinutes' : bigint,
  'exerciseName' : string,
  'takeoffTime' : string,
  'landingTime' : string,
  'landingType' : string,
  'landingCount' : bigint,
  'instructorName' : string,
}
export interface Instructor {
  'name' : string,
  'email' : string,
  'rating' : string,
  'phone' : string,
  'certificateNumber' : string,
}
export interface MonthlySummary {
  'month' : string,
  'totalFlights' : bigint,
  'totalHours' : number,
}
export interface Student {
  'totalFlightHours' : bigint,
  'name' : string,
  'email' : string,
  'medicalExpiry' : string,
  'licenseNumber' : string,
  'phone' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAircraft' : ActorMethod<[Aircraft], string>,
  'addExercise' : ActorMethod<[Exercise], string>,
  'addInstructor' : ActorMethod<[Instructor], string>,
  'addStudent' : ActorMethod<[Student], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFlightLog' : ActorMethod<[FlightLog], bigint>,
  'createOrGetProfile' : ActorMethod<[UserProfile], UserProfile>,
  'deleteAircraft' : ActorMethod<[string], undefined>,
  'deleteExercise' : ActorMethod<[string], undefined>,
  'deleteFlightLog' : ActorMethod<[bigint], undefined>,
  'deleteInstructor' : ActorMethod<[string], undefined>,
  'deleteStudent' : ActorMethod<[string], undefined>,
  'getAllAircrafts' : ActorMethod<[], Array<Aircraft>>,
  'getAllExercises' : ActorMethod<[], Array<Exercise>>,
  'getAllFlightLogs' : ActorMethod<[], Array<FlightLog>>,
  'getAllInstructors' : ActorMethod<[], Array<Instructor>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllUsersWithProfiles' : ActorMethod<[], Array<AdminUserInfo>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailySummary' : ActorMethod<[string], DailySummary>,
  'getFlightLogById' : ActorMethod<[bigint], [] | [FlightLog]>,
  'getFlightLogsByAircraft' : ActorMethod<[string], Array<FlightLog>>,
  'getFlightLogsByDateRange' : ActorMethod<[string, string], Array<FlightLog>>,
  'getFlightLogsByInstructor' : ActorMethod<[string], Array<FlightLog>>,
  'getFlightLogsByMonth' : ActorMethod<[string], Array<FlightLog>>,
  'getFlightLogsByStudent' : ActorMethod<[string], Array<FlightLog>>,
  'getMonthlySummary' : ActorMethod<[string], MonthlySummary>,
  'getTotalHoursPerAircraft' : ActorMethod<[], Array<AircraftHours>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAircraft' : ActorMethod<[string, Aircraft], undefined>,
  'updateExercise' : ActorMethod<[string, Exercise], undefined>,
  'updateFlightLog' : ActorMethod<[FlightLog], undefined>,
  'updateInstructor' : ActorMethod<[string, Instructor], undefined>,
  'updateStudent' : ActorMethod<[string, Student], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];