/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    difficultyLevel: string;
    name: string;
    description: string;
    durationMinutes: bigint;
}
export interface DailySummary {
    totalFlights: bigint;
    totalHours: number;
    date: string;
}
export interface Instructor {
    name: string;
    email: string;
    rating: string;
    phone: string;
    certificateNumber: string;
}
export interface AircraftHours {
    totalHours: number;
    registration: string;
}
export interface AdminUserInfo {
    principal: Principal;
    role: UserRole;
    profile: UserProfile;
}
export interface MonthlySummary {
    month: string;
    totalFlights: bigint;
    totalHours: number;
}
export interface FlightLog {
    id: bigint;
    aircraftRegistration: string;
    studentName: string;
    date: string;
    flightType: string;
    durationMinutes: bigint;
    exerciseName: string;
    takeoffTime: string;
    landingTime: string;
    landingType: string;
    landingCount: bigint;
    instructorName: string;
}
export interface Aircraft {
    totalAirframeHours: bigint;
    registration: string;
    hourlyRate: bigint;
    makeModel: string;
    lastMaintenanceDate: string;
}
export interface UserProfile {
    name: string;
}
export interface Student {
    totalFlightHours: bigint;
    name: string;
    email: string;
    medicalExpiry: string;
    licenseNumber: string;
    phone: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAircraft(aircraft: Aircraft): Promise<string>;
    addExercise(exercise: Exercise): Promise<string>;
    addInstructor(instructor: Instructor): Promise<string>;
    addStudent(student: Student): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignUserRole(user: Principal, role: UserRole): Promise<void>;
    createFlightLog(log: FlightLog): Promise<bigint>;
    createOrGetProfile(profile: UserProfile): Promise<UserProfile>;
    deleteAircraft(registration: string): Promise<void>;
    deleteExercise(name: string): Promise<void>;
    deleteFlightLog(id: bigint): Promise<void>;
    deleteInstructor(name: string): Promise<void>;
    deleteStudent(name: string): Promise<void>;
    getAllAircrafts(): Promise<Array<Aircraft>>;
    getAllExercises(): Promise<Array<Exercise>>;
    getAllFlightLogs(): Promise<Array<FlightLog>>;
    getAllInstructors(): Promise<Array<Instructor>>;
    getAllStudents(): Promise<Array<Student>>;
    getAllUsersWithProfiles(): Promise<Array<AdminUserInfo>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailySummary(date: string): Promise<DailySummary>;
    getFlightLogById(id: bigint): Promise<FlightLog | null>;
    getFlightLogsByAircraft(registration: string): Promise<Array<FlightLog>>;
    getFlightLogsByDateRange(startDate: string, endDate: string): Promise<Array<FlightLog>>;
    getFlightLogsByInstructor(instructorName: string): Promise<Array<FlightLog>>;
    getFlightLogsByMonth(month: string): Promise<Array<FlightLog>>;
    getFlightLogsByStudent(studentName: string): Promise<Array<FlightLog>>;
    getMonthlySummary(month: string): Promise<MonthlySummary>;
    getTotalHoursPerAircraft(): Promise<Array<AircraftHours>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAircraft(oldReg: string, newAircraft: Aircraft): Promise<void>;
    updateExercise(oldName: string, newExercise: Exercise): Promise<void>;
    updateFlightLog(log: FlightLog): Promise<void>;
    updateInstructor(oldName: string, newInstructor: Instructor): Promise<void>;
    updateStudent(oldName: string, newStudent: Student): Promise<void>;
}
import type { AdminUserInfo as _AdminUserInfo, FlightLog as _FlightLog, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAircraft(arg0: Aircraft): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addAircraft(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAircraft(arg0);
            return result;
        }
    }
    async addExercise(arg0: Exercise): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addExercise(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExercise(arg0);
            return result;
        }
    }
    async addInstructor(arg0: Instructor): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addInstructor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInstructor(arg0);
            return result;
        }
    }
    async addStudent(arg0: Student): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createFlightLog(arg0: FlightLog): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createFlightLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFlightLog(arg0);
            return result;
        }
    }
    async createOrGetProfile(arg0: UserProfile): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrGetProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrGetProfile(arg0);
            return result;
        }
    }
    async deleteAircraft(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAircraft(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAircraft(arg0);
            return result;
        }
    }
    async deleteExercise(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExercise(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExercise(arg0);
            return result;
        }
    }
    async deleteFlightLog(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFlightLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFlightLog(arg0);
            return result;
        }
    }
    async deleteInstructor(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInstructor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInstructor(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async getAllAircrafts(): Promise<Array<Aircraft>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAircrafts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAircrafts();
            return result;
        }
    }
    async getAllExercises(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExercises();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExercises();
            return result;
        }
    }
    async getAllFlightLogs(): Promise<Array<FlightLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFlightLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFlightLogs();
            return result;
        }
    }
    async getAllInstructors(): Promise<Array<Instructor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInstructors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInstructors();
            return result;
        }
    }
    async getAllStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return result;
        }
    }
    async getAllUsersWithProfiles(): Promise<Array<AdminUserInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsersWithProfiles();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsersWithProfiles();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailySummary(arg0: string): Promise<DailySummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailySummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailySummary(arg0);
            return result;
        }
    }
    async getFlightLogById(arg0: bigint): Promise<FlightLog | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlightLogById(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlightLogById(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFlightLogsByAircraft(arg0: string): Promise<Array<FlightLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlightLogsByAircraft(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlightLogsByAircraft(arg0);
            return result;
        }
    }
    async getFlightLogsByDateRange(arg0: string, arg1: string): Promise<Array<FlightLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlightLogsByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlightLogsByDateRange(arg0, arg1);
            return result;
        }
    }
    async getFlightLogsByInstructor(arg0: string): Promise<Array<FlightLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlightLogsByInstructor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlightLogsByInstructor(arg0);
            return result;
        }
    }
    async getFlightLogsByMonth(arg0: string): Promise<Array<FlightLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlightLogsByMonth(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlightLogsByMonth(arg0);
            return result;
        }
    }
    async getFlightLogsByStudent(arg0: string): Promise<Array<FlightLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlightLogsByStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlightLogsByStudent(arg0);
            return result;
        }
    }
    async getMonthlySummary(arg0: string): Promise<MonthlySummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlySummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlySummary(arg0);
            return result;
        }
    }
    async getTotalHoursPerAircraft(): Promise<Array<AircraftHours>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalHoursPerAircraft();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalHoursPerAircraft();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateAircraft(arg0: string, arg1: Aircraft): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAircraft(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAircraft(arg0, arg1);
            return result;
        }
    }
    async updateExercise(arg0: string, arg1: Exercise): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExercise(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExercise(arg0, arg1);
            return result;
        }
    }
    async updateFlightLog(arg0: FlightLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFlightLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFlightLog(arg0);
            return result;
        }
    }
    async updateInstructor(arg0: string, arg1: Instructor): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInstructor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInstructor(arg0, arg1);
            return result;
        }
    }
    async updateStudent(arg0: string, arg1: Student): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AdminUserInfo_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminUserInfo): AdminUserInfo {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FlightLog]): FlightLog | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    role: _UserRole;
    profile: _UserProfile;
}): {
    principal: Principal;
    role: UserRole;
    profile: UserProfile;
} {
    return {
        principal: value.principal,
        role: from_candid_UserRole_n6(_uploadFile, _downloadFile, value.role),
        profile: value.profile
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminUserInfo>): Array<AdminUserInfo> {
    return value.map((x)=>from_candid_AdminUserInfo_n4(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
